from typing import Dict, Set
from .Locations import all_location_data


class FezRegionData:
    def __init__(self, name: str, exits: Set[str]):
        self.name = name
        self.exits = exits

all_region_data: Set[FezRegionData] = {
    FezRegionData("Abandoned A", {"Villageville 3D"}),
    FezRegionData("Abandoned B", {"Villageville 3D"}),
    FezRegionData("Abandoned C", {"Villageville 3D"}),
    FezRegionData("Ancient Walls", {"Bell Tower", "Wall Hole", "Zu Tetris"}),
    FezRegionData("Arch", {"Five Towers", "Nature Hub", "Zu Switch", "Weightswitch Temple"}),
    FezRegionData("Bell Tower", {"Water Pyramid", "Nature Hub", "Quantum", "Ancient Walls", "Five Towers"}),
    FezRegionData("Big Owl", {"Owl"}),
    FezRegionData("Big Tower", {"Villageville 3D", "Memory Core"}),
    FezRegionData("Boileroom", {"Villageville 3D"}),
    FezRegionData("Cabin Interior A", {"Tree"}),
    FezRegionData("Cabin Interior B", {"Graveyard Cabin"}),
    FezRegionData("Clock", {"Zu City Ruins", "Zu Library"}),
    FezRegionData("CMY B", {"CMY"}),
    FezRegionData("CMY Fork", {"Waterfall", "CMY B", "CMY"}),
    FezRegionData("CMY", {"Waterfall", "CMY B", "CMY Fork"}),
    FezRegionData("Code Machine", {"Visitor"}),
    FezRegionData("Crypt", {"Mausoleum", "Tree of Death"}),
    FezRegionData("Elders", {"Gomez House"}),
    FezRegionData("Extractor A", {"Pivot 2"}),
    FezRegionData("Five Towers Cave", {"Five Towers"}),
    FezRegionData("Five Towers", {"Arch", "Five Towers Cave", "Bell Tower"}),
    FezRegionData("Fox", {"Waterfall"}),
    FezRegionData("Fractal", {"Two Walls", "Zu 4 Side"}),
    FezRegionData("Geezer House 2D", {"Villageville 2D"}),
    FezRegionData("Geezer House", {"Villageville 3D"}),
    FezRegionData("Globe Interior", {"Globe"}),
    FezRegionData("Globe", {"Library Interior", "Globe Interior"}),
    FezRegionData("Gomez House 2D", {"Villageville 2D"}),
    FezRegionData("Gomez House End 32", {"Villageville 3D End 32"}),
    FezRegionData("Gomez House End 64", {"Villageville 3D End 64"}),
    FezRegionData("Gomez House", {"Villageville 3D"}),
    FezRegionData("Graveyard Cabin", {"Cabin Interior A", "Graveyard Gate"}),
    FezRegionData("Graveyard Ghost", {"Mausoleum"}),
    FezRegionData("Graveyard Lesser Gate", {"Graveyard A"}),
    FezRegionData("Graveyard Treasure A", {"Graveyard A"}),
    FezRegionData("Graveyard A", {"Graveyard Lesser Gate", "Graveyard Treasure A", "Mausoleum"}),
    FezRegionData("Graveyard Gate", {"Graveyard Cabin", "Skull", "Owl", "Mausoleum"}),
    FezRegionData("Hex Rebuild", {"Pyramid", "Gomez House End 32", "Gomez House End 64"}),
    FezRegionData("Industrial Abandoned A", {"Industrial Hub"}),
    FezRegionData("Industrial City", {"Memory Core", "Nu Zu School", "Nu Zu Boileroom", "Nu Zu Abandoned A", "Showers", "Nu Zu Dormitory"}),
    FezRegionData("Industrial Hub", {"Industrial Superspin", "Rails", "Pivot 1", "Pivot Watertower", "Industrial Abandoned A", "Nu Zu Abandoned B", "Well 2"}),
    FezRegionData("Industrial Superspin", {"Industrial Hub", "Superspin Cave"}),
    FezRegionData("Kitchen 2D", {"Villageville 2D"}),
    FezRegionData("Kitchen", {"Villageville 3D"}),
    FezRegionData("Lava Fork", {"Lava"}),
    FezRegionData("Lava Skull", {"Lava"}),
    FezRegionData("Lava", {"Sewer to Lava", "Lava Skull", "Lava Fork"}),
    FezRegionData("Library Interior", {"Zu Library", "Globe"}),
    # Lighthouse has an upper and lower portion which require access through the inside levels
    FezRegionData("Lighthouse House A", {"_LighthouseLower", "Lighthouse Spin"}),
    FezRegionData("Lighthouse Spin", {"Lighthouse House A", "_LighthouseUpper"}),
    FezRegionData("_LighthouseLower", {"Lighthouse House A", "Nature Hub", "Zu Fork"}),
    FezRegionData("_LighthouseUpper", {"_LighthouseLower", "Lighthouse Spin", "Water Tower"}),
    FezRegionData("Mausoleum", {"Graveyard A", "Graveyard Gate", "Crypt", "Graveyard Ghost", "Tree Roots"}),
    FezRegionData("Memory Core", {"Big Tower", "Nature Hub", "Wall Village", "Industrial City", "Zu City", "Pivot Watertower"}),
    FezRegionData("Mine A", {"Waterfall", "Mine Wrap"}),
    FezRegionData("Mine Bomb Pillar", {"Mine Wrap"}),
    FezRegionData("Mine Wrap", {"Mine A", "Mine Bomb Pillar"}),
    FezRegionData("Nature Hub", {"Waterfall", "_LighthouseLower", "Arch", "Bell Tower", "Memory Core", "Tree Roots", "Ritual", "Two Walls"}),
    FezRegionData("Nu Zu Abandoned A", {"Industrial City"}),
    FezRegionData("Nu Zu Abandoned B", {"Industrial Hub", "Sewer to Lava"}),
    FezRegionData("Nu Zu Boileroom", {"Industrial City"}),
    FezRegionData("Nu Zu Dormitory", {"Industrial City"}),
    FezRegionData("Nu Zu School", {"Industrial City"}),
    FezRegionData("Observatory", {"Zu City Ruins", "Telescope", "Visitor", "Throne"}),
    FezRegionData("Oldschool Ruins", {"Zu City Ruins"}),
    FezRegionData("Oldschool", {"Zu City"}),
    FezRegionData("Orrery B", {"Orrery"}),
    FezRegionData("Orrery", {"Visitor", "Orrery B"}),
    FezRegionData("Owl", {"Graveyard Gate", "Big Owl"}),
    FezRegionData("Parlor 2D", {"Villageville 2D"}),
    FezRegionData("Parlor", {"Villageville 3D"}),
    FezRegionData("Pivot 1", {"Windmill Interior", "Industrial Hub", "Pivot 2"}),
    FezRegionData("Pivot 2", {"Pivot 3", "Extractor A", "Pivot 1"}),
    FezRegionData("Pivot 3", {"Pivot 1", "Pivot 3 Cave"}),
    FezRegionData("Pivot 3 Cave", {"Pivot 3"}),
    FezRegionData("Pivot Watertower", {"Water Tower", "Industrial Hub", "Memory Core"}),
    FezRegionData("Purple Lodge Ruin", {"Zu City Ruins", "Visitor"}),
    FezRegionData("Purple Lodge", {"Zu City"}),
    FezRegionData("Pyramid", {"Stargate", "Hex Rebuild"}),
    FezRegionData("Quantum", {"Bell Tower"}),
    FezRegionData("Rails", {"Well 2", "Industrial Hub", "Triple Pivot Cave"}),
    FezRegionData("Ritual", {"Nature Hub"}),
    FezRegionData("School 2D", {"Villageville 2D"}),
    FezRegionData("School", {"Villageville 3D"}),
    FezRegionData("Sewer Fork", {"Sewer Pillars", "Sewer Hub"}),
    FezRegionData("Sewer Geyser", {"Sewer Pillars", "Sewer Hub"}),
    FezRegionData("Sewer Hub", {"Sewer Treasure 1", "Sewer Pivot", "Sewer to Lava", "Sewer Geyser", "Sewer Start", "Sewer QR", "Sewer Fork"}),
    FezRegionData("Sewer Lesser Gate B", {"Sewer Pillars"}),
    FezRegionData("Sewer Pillars", {"Sewer Fork", "Sewer Treasure 2", "Sewer Lesser Gate B", "Sewer Geyser"}),
    FezRegionData("Sewer Pivot", {"Sewer Hub"}),
    FezRegionData("Sewer QR", {"Sewer Hub", "_ThroneAntiCube"}),
    FezRegionData("Sewer Start", {"Well 2", "Sewer Hub"}),
    FezRegionData("Sewer to Lava", {"Sewer Hub", "Lava", "Nu Zu Abandoned B"}),
    FezRegionData("Sewer Treasure 1", {"Sewer Hub"}),
    FezRegionData("Sewer Treasure 2", {"Sewer Pillars"}),
    FezRegionData("Showers", {"Industrial City"}),
    FezRegionData("Skull B", {"Skull"}),
    FezRegionData("Skull", {"Skull B", "Graveyard Gate"}),
    FezRegionData("Spinning Plates", {"Triple Pivot Cave"}),
    FezRegionData("Stargate Ruins", {"Zu City Ruins"}),
    FezRegionData("Stargate", {"Zu City", "Pyramid"}),
    FezRegionData("Superspin Cave", {"Industrial Superspin"}),
    FezRegionData("Telescope", {"Observatory"}),
    FezRegionData("Temple of Love", {"Water Pyramid"}),
    FezRegionData("Throne", {"Zu Bridge", "Tree Sky", "Zu Unfold", "Zu City Ruins", "Observatory"}),
    FezRegionData("Tree Crumble", {"Tree"}),
    FezRegionData("Tree of Death", {"Crypt"}),
    FezRegionData("Tree Roots", {"Nature Hub", "Tree", "Mausoleum"}),
    FezRegionData("Tree Sky", {"Tree", "Throne"}),
    FezRegionData("Tree", {"Cabin Interior B", "Tree Roots", "Tree Sky", "Tree Crumble"}),
    FezRegionData("Triple Pivot Cave", {"Spinning Plates", "Rails"}),
    FezRegionData("Two Walls", {"Wall Hole", "Fractal", "Nature Hub"}),
    FezRegionData("Villageville 2D", {"Gomez House 2D", "School 2D", "Kitchen 2D", "Parlor 2D", "Geezer House 2D", "Elders"}),
    FezRegionData("Villageville 3D End 32", {"Gomez House End 32"}),
    FezRegionData("Villageville 3D End 64", {"Gomez House End 64"}),
    FezRegionData("Villageville 3D", {"Gomez House", "Boileroom", "School", "Abandoned A", "Parlor", "Big Tower", "Kitchen", "Abandoned B", "Abandoned C", "Geezer House"}),
    FezRegionData("Visitor", {"Orrery", "Observatory", "Code Machine", "Purple Lodge Ruin"}),
    FezRegionData("Wall Hole", {"Ancient Walls", "Two Walls"}),
    FezRegionData("Wall Interior A", {"Wall Village"}),
    FezRegionData("Wall Interior B", {"Wall Village"}),
    FezRegionData("Wall Interior Hole", {"Wall Village"}),
    FezRegionData("Wall Kitchen", {"Wall Village"}),
    FezRegionData("Wall School", {"Wall Village"}),
    FezRegionData("Wall Village", {"Wall Interior A", "Wall Interior B", "Memory Core", "Wall Interior Hole", "Wall Kitchen", "Wall School"}),
    FezRegionData("Water Pyramid", {"Bell Tower", "Temple of Love"}),
    FezRegionData("Water Tower", {"_LighthouseUpper", "Pivot Watertower", "Watertower Secret"}),
    FezRegionData("Water Wheel B", {"Water Wheel"}),
    FezRegionData("Water Wheel", {"Water Wheel B", "Waterfall"}),
    FezRegionData("Waterfall", {"Fox", "Nature Hub", "Water Wheel", "Mine A", "CMY", "Zu Code Loop", "Zu Zuish"}),
    FezRegionData("Watertower Secret", {"Water Tower"}),
    FezRegionData("Weightswitch Temple", {"Zu Switch", "Arch"}),
    FezRegionData("Well 2", {"Sewer Start", "Rails", "Industrial Hub"}),
    FezRegionData("Windmill Cave", {"Windmill Interior"}),
    FezRegionData("Windmill Interior", {"Pivot 1", "Windmill Cave"}),
    FezRegionData("Zu 4 Side", {"Zu Heads", "Fractal"}),
    FezRegionData("Zu Bridge", {"Zu City Ruins", "Throne"}),
    FezRegionData("Zu City Ruins", {"Stargate Ruins", "Observatory", "Clock", "Zu Bridge", "Zu Throne Ruins", "Zu House Ruin Visitors", "Zu House QR", "Throne", "Oldschool Ruins", "Purple Lodge Ruin", "Zu Library"}),
    FezRegionData("Zu City", {"Stargate", "Memory Core", "Oldschool", "Purple Lodge", "Zu House Scaffolding", "Zu House Empty", "Zu House Empty B"}),
    FezRegionData("Zu Code Loop", {"Waterfall"}),
    FezRegionData("Zu Fork", {"_LighthouseLower"}),
    FezRegionData("Zu Heads", {"Zu 4 Side"}),
    FezRegionData("Zu House Empty B", {"Zu City"}),
    FezRegionData("Zu House Empty", {"Zu City", "_ThroneAntiCube"}),
    FezRegionData("Zu House QR", {"Zu City Ruins"}),
    FezRegionData("Zu House Ruin Visitors", {"Zu City Ruins"}),
    FezRegionData("Zu House Scaffolding", {"Zu City"}),
    FezRegionData("Zu Library", {"Library Interior", "Clock", "Zu City Ruins"}),
    FezRegionData("Zu Switch B", {"Zu Switch"}),
    FezRegionData("Zu Switch", {"Weightswitch Temple", "Zu Switch B"}),
    FezRegionData("Zu Tetris", {"Ancient Walls"}),
    FezRegionData("Zu Throne Ruins", {"Zu City Ruins", "_ThroneAntiCube"}),
    FezRegionData("Zu Unfold", {"Throne"}),
    FezRegionData("Zu Zuish", {"Waterfall"}),
    # DRUM, OCTOHEDRON, WATERFALL_ALT and ZU_HOUSE_RUIN_GATE are all not playable and are excluded despite having fezlvl data

    # Mock region to store "Throne Anti-Cube" connected to starting region to avoid dead end
    FezRegionData("_ThroneAntiCube", {"Gomez House"})
}

region_name_to_location_name: Dict[str, Set[str]] = {data.name: set() for data in all_region_data}
for data in all_location_data:
    region_name_to_location_name[data.region_name].add(data.name)
