from typing import Dict, Set
from .Locations import all_location_data


region_name_to_location_name: Dict[str, Set[str]] = {}
for data in all_location_data:
    region_name_to_location_name[data.region_name].union(data.name)


class FezRegionData:
    def __init__(self, name: str, exits: Set[str]):
        self.name = name
        self.exits = exits


# TODO: Add region information
all_region_data: Set[FezRegionData] = {
    FezRegionData("Abandoned A", set()),
    FezRegionData("Abandoned B", set()),
    FezRegionData("Abandoned C", set()),
    FezRegionData("Ancient Walls", set()),
    FezRegionData("Arch", set()),
    FezRegionData("Bell Tower", set()),
    FezRegionData("Big Owl", set()),
    FezRegionData("Big Tower", set()),
    FezRegionData("Boileroom", set()),
    FezRegionData("Cabin Interior A", set()),
    FezRegionData("Cabin Interior B", set()),
    FezRegionData("Clock", set()),
    FezRegionData("CMY B", set()),
    FezRegionData("CMY Fork", set()),
    FezRegionData("CMY", set()),
    FezRegionData("Code Machine", set()),
    FezRegionData("Crypt", set()),
    FezRegionData("Drum", set()),
    FezRegionData("Elders", set()),
    FezRegionData("Extractor A", set()),
    FezRegionData("Five Towers Cave", set()),
    FezRegionData("Five Towers", set()),
    FezRegionData("Fox", set()),
    FezRegionData("Fractal", set()),
    FezRegionData("Geezer House 2D", set()),
    FezRegionData("Gezzer House", set()),
    FezRegionData("Globe Internal", set()),
    FezRegionData("Globe", set()),
    FezRegionData("Gomez House 2D", set()),
    FezRegionData("Gomez House End 32", set()),
    FezRegionData("Gomez House End 64", set()),
    FezRegionData("Gomez House", set()),
    FezRegionData("Graveyard Cabin", set()),
    FezRegionData("Graveyard Ghost", set()),
    FezRegionData("Graveyard Lesser Gate", set()),
    FezRegionData("Graveyard Treasure A", set()),
    FezRegionData("Graveyard A", set()),
    FezRegionData("Graveyard Gate", set()),
    FezRegionData("Hex Rebuild", set()),
    FezRegionData("Industrial Abandoned A", set()),
    FezRegionData("Industrial City", set()),
    FezRegionData("Industrial Hub", set()),
    FezRegionData("Industrial Superspin", set()),
    FezRegionData("Kitchen 2D", set()),
    FezRegionData("Kitchen", set()),
    FezRegionData("Lava Fork", set()),
    FezRegionData("Lava Skull", set()),
    FezRegionData("Library Interior", set()),
    FezRegionData("Lighthouse House A", set()),
    FezRegionData("Lighthouse Spin", set()),
    FezRegionData("Lighthouse", set()),
    FezRegionData("Mausoleum", set()),
    FezRegionData("Memory Core", set()),
    FezRegionData("Mine A", set()),
    FezRegionData("Mine Bomb Pillar", set()),
    FezRegionData("Mine Wrap", set()),
    FezRegionData("Nature Hub", set()),
    FezRegionData("Nuzu Abandoned A", set()),
    FezRegionData("Nuzu Abandoned B", set()),
    FezRegionData("Nuzu Boileroom", set()),
    FezRegionData("Nuzu Dormitory", set()),
    FezRegionData("Nuzu School", set()),
    FezRegionData("Observatory", set()),
    FezRegionData("Octohedron", set()),
    FezRegionData("Oldschool Ruins", set()),
    FezRegionData("Oldschool", set()),
    FezRegionData("Orrery B", set()),
    FezRegionData("Orrery", set()),
    FezRegionData("Owl", set()),
    FezRegionData("Parlor 2D", set()),
    FezRegionData("Parlor", set()),
    FezRegionData("Pivot 1", set()),
    FezRegionData("Pivot 2", set()),
    FezRegionData("Pivot 3", set()),
    FezRegionData("Pivot 3 Cave", set()),
    FezRegionData("Pivot Watertower", set()),
    FezRegionData("Purple Lodge Ruin", set()),
    FezRegionData("Purple Lodge", set()),
    FezRegionData("Pyramid", set()),
    FezRegionData("Quantum", set()),
    FezRegionData("Rails", set()),
    FezRegionData("Ritual", set()),
    FezRegionData("School 2D", set()),
    FezRegionData("School", set()),
    FezRegionData("Sewer Fork", set()),
    FezRegionData("Sewer Geyser", set()),
    FezRegionData("Sewer Hub", set()),
    FezRegionData("Sewer Lesser Gate B", set()),
    FezRegionData("Sewer Pillars", set()),
    FezRegionData("Sewer Pivot", set()),
    FezRegionData("Sewer QR", set()),
    FezRegionData("Sewer Start", set()),
    FezRegionData("Sewer to Lava", set()),
    FezRegionData("Sewer Treasure 1", set()),
    FezRegionData("Sewer Treasure 2", set()),
    FezRegionData("Showers", set()),
    FezRegionData("Skull B", set()),
    FezRegionData("Skull", set()),
    FezRegionData("Spinning Plates", set()),
    FezRegionData("Stargate Ruins", set()),
    FezRegionData("Stargate", set()),
    FezRegionData("Superspin Cave", set()),
    FezRegionData("Telescope", set()),
    FezRegionData("Temple of Love", set()),
    FezRegionData("Throne", set()),
    FezRegionData("Tree Crumble", set()),
    FezRegionData("Tree of Death", set()),
    FezRegionData("Tree Roots", set()),
    FezRegionData("Tree Sky", set()),
    FezRegionData("Tree", set()),
    FezRegionData("Triple Pivot Cave", set()),
    FezRegionData("Two Walls", set()),
    FezRegionData("Villageville 2D", set()),
    FezRegionData("Villageville 3D End 32", set()),
    FezRegionData("Villageville 3D End 64", set()),
    FezRegionData("Villageville 3D", set()),
    FezRegionData("Visitor", set()),
    FezRegionData("Wall Hole", set()),
    FezRegionData("Wall Interior A", set()),
    FezRegionData("Wall Interior B", set()),
    FezRegionData("Wall Interior Hole", set()),
    FezRegionData("Wall Kitchen", set()),
    FezRegionData("Wall School", set()),
    FezRegionData("Wall Village", set()),
    FezRegionData("Water Pyramid", set()),
    FezRegionData("Water Tower", set()),
    FezRegionData("Water Wheel B", set()),
    FezRegionData("Water Wheel", set()),
    FezRegionData("Waterfall Alt", set()),
    FezRegionData("Waterfall", set()),
    FezRegionData("Watertower Secret", set()),
    FezRegionData("Weightswitch Temple", set()),
    FezRegionData("Well 2", set()),
    FezRegionData("Windmill Cave", set()),
    FezRegionData("Windmill Interior", set()),
    FezRegionData("Zu 4 Side", set()),
    FezRegionData("Zu Bridge", set()),
    FezRegionData("Zu City Ruins", set()),
    FezRegionData("Zu City", set()),
    FezRegionData("Zu Code Loop", set()),
    FezRegionData("Zu Fork", set()),
    FezRegionData("Zu Heads", set()),
    FezRegionData("Zu House Empty B", set()),
    FezRegionData("Zu House Empty", set()),
    FezRegionData("Zu House QR", set()),
    FezRegionData("Zu House Ruin Gate", set()),
    FezRegionData("Zu House Ruin Visitors", set()),
    FezRegionData("Zu House Scaffolding", set()),
    FezRegionData("Zu Library", set()),
    FezRegionData("Zu Switch B", set()),
    FezRegionData("Zu Switch", set()),
    FezRegionData("Zu Tetris", set()),
    FezRegionData("Zu Throne Ruins", set()),
    FezRegionData("Zu Unfold", set()),
    FezRegionData("Zu Zuish", set())
}
